export enum ProfessionCode {
  STUDENT = 'STUDENT',
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  ENGINEER = 'ENGINEER',
  TEACHER = 'TEACHER',
  ACCOUNTANT = 'ACCOUNTANT',
  IT_PROFESSIONAL = 'IT_PROFESSIONAL',
  LAWYER = 'LAWYER',
  BUSINESS_PROFESSIONAL = 'BUSINESS_PROFESSIONAL',
  OTHER = 'OTHER',
}
